"""Research diary auto-generator — every significant finding becomes a dated,
2-page markdown entry that (a) documents the finding, (b) records the
prediction, (c) becomes a preprint section later.

Output structure:
  diary/
    YYYY-MM-DD_hypothesis_NNN.md  (one per surviving hypothesis)
    YYYY-MM-DD_cycle_NNN.md       (one per detected cycle)
    YYYY-MM-DD_signal_NNN.md      (one per inverse signal)
    weekly/
      YYYY-WNN.md                 (weekly rollup — auto-compiled)
    monthly/
      YYYY-MM.md                  (monthly rollup — preprint section)

Pure-Python. No LLM calls. Every entry is deterministic from the DB, so
re-running regenerates identical entries.

Usage:
    python research_diary.py                  # incremental: new entries only
    python research_diary.py --all            # regenerate everything
    python research_diary.py weekly           # build this week's rollup
    python research_diary.py monthly          # build this month's rollup
    python research_diary.py preprint         # compile all monthlies into
                                              # preprint-sections/SectionN.md
"""

import json
import sys
from datetime import datetime, timedelta
from pathlib import Path

from database import get_connection


HERE = Path(__file__).parent
DIARY_ROOT = HERE / "diary"
WEEKLY_DIR = DIARY_ROOT / "weekly"
MONTHLY_DIR = DIARY_ROOT / "monthly"
PREPRINT_DIR = DIARY_ROOT / "preprint-sections"


def _ensure_dirs():
    for d in (DIARY_ROOT, WEEKLY_DIR, MONTHLY_DIR, PREPRINT_DIR):
        d.mkdir(parents=True, exist_ok=True)


# ══════════════════════════════════════════════════════════════════════
# Per-finding entries
# ══════════════════════════════════════════════════════════════════════

def _hypothesis_to_markdown(h: dict) -> str:
    """Render a surviving hypothesis as a 2-page markdown entry."""
    score = h.get("diamond_score") or 0
    created = str(h.get("created_at", ""))[:10]
    hid = h.get("id")

    # Parse fact_chain
    try:
        fact_chain = json.loads(h.get("fact_chain") or "[]")
    except json.JSONDecodeError:
        fact_chain = []
    try:
        kill_attempts = json.loads(h.get("kill_attempts") or "[]")
    except json.JSONDecodeError:
        kill_attempts = []

    lines = []
    lines.append(f"# Hypothesis #{hid} — score {score}")
    lines.append(f"*Dated {created}. Survived kill phase. Evidence level: {h.get('confidence', 'Medium')}*\n")
    lines.append("## The claim\n")
    lines.append((h.get("hypothesis_text") or "").strip())
    lines.append("\n## Fact chain\n")
    for i, f in enumerate(fact_chain, 1):
        if isinstance(f, dict):
            fid = f.get("fact_id", "?")
            role = f.get("role", "")
            lines.append(f"**{i}.** Fact #{fid}: {role}")
    lines.append("\n## Scoring breakdown\n")
    lines.append(f"- Novelty: {h.get('novelty', '?')} / 20")
    lines.append(f"- Feasibility: {h.get('feasibility', '?')} / 20")
    lines.append(f"- Timing: {h.get('timing', '?')} / 20")
    lines.append(f"- Asymmetry: {h.get('asymmetry', '?')} / 20")
    lines.append(f"- Intersection: {h.get('intersection', '?')} / 20")
    lines.append(f"- Total: **{score}/100**")
    lines.append("\n## Kill attempts\n")
    for k in kill_attempts:
        if not isinstance(k, dict):
            continue
        verdict = "KILLED" if k.get("killed") else "SURVIVED"
        lines.append(f"- Round **{k.get('round', '?')}** [{k.get('kill_type', '?')}]: {verdict} — {(k.get('reason') or '')[:200]}")
    lines.append("\n## Action steps\n")
    lines.append((h.get("action_steps") or "").strip() or "_not recorded_")
    lines.append(f"\n## Prediction window\n")
    lines.append(f"- Time window: {h.get('time_window_days', 90)} days from {created}")
    lines.append(f"- Expected resolution: {(datetime.strptime(created, '%Y-%m-%d') + timedelta(days=int(h.get('time_window_days') or 90))).strftime('%Y-%m-%d') if created else 'unknown'}")
    lines.append("\n## Outcome")
    lines.append("*To be filled in when resolution window closes.*\n")
    lines.append(f"\n---\n*Auto-generated by research_diary.py. Source: hunter.db hypotheses row {hid}.*")
    return "\n".join(lines)


def _cycle_to_markdown(c: dict) -> str:
    cid = c.get("id")
    try:
        nodes = json.loads(c.get("nodes") or "[]")
    except json.JSONDecodeError:
        nodes = []
    try:
        domains = json.loads(c.get("domains") or "[]")
    except json.JSONDecodeError:
        domains = []

    detected = str(c.get("detected_date", ""))[:10]
    lines = []
    lines.append(f"# Cycle #{cid} — {c.get('cycle_type', 'unknown')}")
    lines.append(f"*Detected {detected}. Reinforcement strength: {c.get('reinforcement_strength', 0):.2f}*\n")
    lines.append(f"## Type\n**{c.get('cycle_type', '?')}** ({len(nodes)} nodes, {len(domains)} distinct domains)\n")
    lines.append("## Loop\n")
    for i, n in enumerate(nodes, 1):
        dom = n.get("domain", "?") if isinstance(n, dict) else "?"
        meth = n.get("methodology", "") if isinstance(n, dict) else ""
        lines.append(f"{i}. **{dom[:80]}**  \n   _{meth[:200]}_")
    lines.append("\n## Persistence prediction\n")
    pe = c.get("persistence_estimate") or 0
    lines.append(f"- Estimated persistence: **{pe:.0f} days**")
    lines.append(f"- Framework predicts reinforcement ≥ correction (stable equilibrium)")
    lines.append(f"- Test: re-detect in {max(7, int(pe * 0.3))} days, {max(14, int(pe * 0.6))} days, {int(pe)} days")
    lines.append("\n## Domains traversed\n")
    for d in domains:
        lines.append(f"- {d}")
    lines.append("\n## Trading implication\n")
    lines.append("If cycle persists as predicted, coordinated positions across nodes should produce alpha. See `cycle_portfolio.py` for implementation (future).\n")
    lines.append("\n## Outcome")
    lines.append("*To be filled in as persistence windows resolve.*\n")
    lines.append(f"\n---\n*Auto-generated by research_diary.py. Source: detected_cycles row {cid}.*")
    return "\n".join(lines)


def _signal_to_markdown(s: dict) -> str:
    sid = s.get("id")
    emitted = str(s.get("emitted_at", ""))[:10]
    lines = []
    lines.append(f"# Inverse Signal #{sid} — {s.get('asset', '?')} {s.get('signal_direction', '?').upper()}")
    lines.append(f"*Emitted {emitted}. Contradiction score: {s.get('contradiction_score', 0):.2f}. Strength: {s.get('signal_strength', '?')}.*\n")
    lines.append("## Belief being shorted\n")
    lines.append(f"> {s.get('target_published_value', '')}\n")
    lines.append("## Assumption claimed to be false\n")
    lines.append(s.get("assumption_claim", "") or "_not recorded_")
    lines.append("\n## Contradicting fact\n")
    lines.append(f"Fact ID: {s.get('contradicting_fact_id', '?')}")
    lines.append(f"\nReasoning: {s.get('reasoning', '')}")
    lines.append("\n## Directional signal\n")
    lines.append(f"- Direction: **{s.get('signal_direction', '?').upper()}** (vs published belief)")
    lines.append(f"- Strength: {s.get('signal_strength', '?')}")
    lines.append("\n## Prediction\n")
    lines.append("The published number will be revised in the direction of the contradicting fact within the belief's target date window.\n")
    lines.append("## Outcome")
    lines.append("*To be filled in when published number is revised or target date passes.*\n")
    lines.append(f"\n---\n*Auto-generated by research_diary.py. Source: inverse_signals row {sid}.*")
    return "\n".join(lines)


# ══════════════════════════════════════════════════════════════════════
# Generate per-finding entries
# ══════════════════════════════════════════════════════════════════════

def generate_hypothesis_entries(force_all: bool = False) -> int:
    conn = get_connection()
    try:
        rows = conn.execute("""
            SELECT id, hypothesis_text, fact_chain, action_steps, time_window_days,
                   kill_attempts, diamond_score, novelty, feasibility, timing,
                   asymmetry, intersection, confidence, created_at
            FROM hypotheses
            WHERE survived_kill = 1 AND diamond_score >= 60
            ORDER BY id
        """).fetchall()
    finally:
        conn.close()

    count = 0
    for row in rows:
        h = dict(zip(
            ["id", "hypothesis_text", "fact_chain", "action_steps", "time_window_days",
             "kill_attempts", "diamond_score", "novelty", "feasibility", "timing",
             "asymmetry", "intersection", "confidence", "created_at"], row))
        created = str(h.get("created_at", ""))[:10] or datetime.now().strftime("%Y-%m-%d")
        filename = DIARY_ROOT / f"{created}_hypothesis_{h['id']:03d}.md"
        if filename.exists() and not force_all:
            continue
        filename.write_text(_hypothesis_to_markdown(h))
        count += 1
    return count


def generate_cycle_entries(force_all: bool = False) -> int:
    conn = get_connection()
    try:
        rows = conn.execute("""
            SELECT id, cycle_type, nodes, domains, reinforcement_strength,
                   correction_pressure, persistence_estimate, detected_date, is_active
            FROM detected_cycles
            ORDER BY id
        """).fetchall()
    finally:
        conn.close()

    count = 0
    for row in rows:
        c = dict(zip(
            ["id", "cycle_type", "nodes", "domains", "reinforcement_strength",
             "correction_pressure", "persistence_estimate", "detected_date", "is_active"], row))
        detected = str(c.get("detected_date", ""))[:10] or datetime.now().strftime("%Y-%m-%d")
        filename = DIARY_ROOT / f"{detected}_cycle_{c['id']:03d}.md"
        if filename.exists() and not force_all:
            continue
        filename.write_text(_cycle_to_markdown(c))
        count += 1
    return count


def generate_signal_entries(force_all: bool = False) -> int:
    conn = get_connection()
    try:
        # Check if inverse_signals table exists
        rows = conn.execute("""
            SELECT name FROM sqlite_master WHERE type='table' AND name='inverse_signals'
        """).fetchall()
        if not rows:
            return 0
        rows = conn.execute("""
            SELECT id, belief_id, assumption_claim, contradicting_fact_id,
                   contradiction_score, signal_direction, signal_strength,
                   reasoning, asset, target_published_value, emitted_at
            FROM inverse_signals
            ORDER BY id
        """).fetchall()
    finally:
        conn.close()

    count = 0
    for row in rows:
        s = dict(zip(
            ["id", "belief_id", "assumption_claim", "contradicting_fact_id",
             "contradiction_score", "signal_direction", "signal_strength",
             "reasoning", "asset", "target_published_value", "emitted_at"], row))
        emitted = str(s.get("emitted_at", ""))[:10] or datetime.now().strftime("%Y-%m-%d")
        filename = DIARY_ROOT / f"{emitted}_signal_{s['id']:03d}.md"
        if filename.exists() and not force_all:
            continue
        filename.write_text(_signal_to_markdown(s))
        count += 1
    return count


# ══════════════════════════════════════════════════════════════════════
# Weekly / monthly rollups
# ══════════════════════════════════════════════════════════════════════

def build_weekly_rollup(iso_week: str = None) -> Path:
    today = datetime.now()
    if iso_week is None:
        iso_week = today.strftime("%Y-W%U")
    week_start = datetime.strptime(iso_week + "-0", "%Y-W%U-%w")
    week_end = week_start + timedelta(days=7)

    conn = get_connection()
    try:
        stats = {
            "new_facts": conn.execute(
                "SELECT COUNT(*) FROM raw_facts WHERE ingested_at BETWEEN ? AND ?",
                (week_start.isoformat(), week_end.isoformat())
            ).fetchone()[0],
            "new_collisions": conn.execute(
                "SELECT COUNT(*) FROM collisions WHERE created_at BETWEEN ? AND ?",
                (week_start.isoformat(), week_end.isoformat())
            ).fetchone()[0],
            "new_survivors": conn.execute(
                "SELECT COUNT(*) FROM hypotheses WHERE created_at BETWEEN ? AND ? AND survived_kill=1",
                (week_start.isoformat(), week_end.isoformat())
            ).fetchone()[0],
        }
        # Top findings this week
        top = conn.execute("""
            SELECT id, hypothesis_text, diamond_score FROM hypotheses
            WHERE survived_kill=1 AND created_at BETWEEN ? AND ?
            ORDER BY diamond_score DESC LIMIT 5
        """, (week_start.isoformat(), week_end.isoformat())).fetchall()
    finally:
        conn.close()

    lines = []
    lines.append(f"# Week {iso_week} — HUNTER research log\n")
    lines.append(f"*{week_start.strftime('%Y-%m-%d')} through {(week_end - timedelta(days=1)).strftime('%Y-%m-%d')}*\n")
    lines.append(f"## This week's numbers\n")
    lines.append(f"- New facts ingested: **{stats['new_facts']:,}**")
    lines.append(f"- New collisions formed: **{stats['new_collisions']}**")
    lines.append(f"- New hypotheses surviving kill: **{stats['new_survivors']}**")
    lines.append(f"\n## Top findings this week\n")
    if not top:
        lines.append("_No new surviving hypotheses this week._")
    for r in top:
        hid, text, score = r
        lines.append(f"- **[{score}]** Hypothesis #{hid}: {(text or '')[:100]}...")
    lines.append(f"\n## Reflection\n")
    lines.append(f"_Manual prose — edit before publishing._\n")
    lines.append(f"\n---\n*Auto-scaffolded by research_diary.py.*")

    filename = WEEKLY_DIR / f"{iso_week}.md"
    filename.write_text("\n".join(lines))
    return filename


def build_monthly_rollup(year_month: str = None) -> Path:
    today = datetime.now()
    if year_month is None:
        year_month = today.strftime("%Y-%m")
    month_start = datetime.strptime(year_month + "-01", "%Y-%m-%d")
    if month_start.month == 12:
        month_end = datetime(month_start.year + 1, 1, 1)
    else:
        month_end = datetime(month_start.year, month_start.month + 1, 1)

    conn = get_connection()
    try:
        new_facts = conn.execute(
            "SELECT COUNT(*) FROM raw_facts WHERE ingested_at BETWEEN ? AND ?",
            (month_start.isoformat(), month_end.isoformat())
        ).fetchone()[0]
        new_cycles = conn.execute(
            "SELECT COUNT(*) FROM detected_cycles WHERE detected_date BETWEEN ? AND ?",
            (month_start.isoformat(), month_end.isoformat())
        ).fetchone()[0]
        new_survivors = conn.execute(
            "SELECT COUNT(*) FROM hypotheses WHERE survived_kill=1 AND created_at BETWEEN ? AND ?",
            (month_start.isoformat(), month_end.isoformat())
        ).fetchone()[0]
        top = conn.execute("""
            SELECT id, hypothesis_text, diamond_score FROM hypotheses
            WHERE survived_kill=1 AND created_at BETWEEN ? AND ?
            ORDER BY diamond_score DESC LIMIT 8
        """, (month_start.isoformat(), month_end.isoformat())).fetchall()
    finally:
        conn.close()

    lines = []
    lines.append(f"# {month_start.strftime('%B %Y')} — HUNTER monthly research log\n")
    lines.append(f"## Monthly numbers\n")
    lines.append(f"- New facts: **{new_facts:,}**")
    lines.append(f"- New cycles detected: **{new_cycles}**")
    lines.append(f"- New surviving hypotheses: **{new_survivors}**")
    lines.append(f"\n## Best findings this month\n")
    for r in top:
        hid, text, score = r
        lines.append(f"### [{score}] Hypothesis #{hid}\n\n{(text or '')[:500]}\n")
    lines.append(f"\n## Monthly interpretation\n_Manual prose — use this as preprint-section source._\n")
    lines.append(f"\n---\n*Auto-scaffolded. Edit and export to `preprint-sections/`.*")

    filename = MONTHLY_DIR / f"{year_month}.md"
    filename.write_text("\n".join(lines))
    return filename


# ══════════════════════════════════════════════════════════════════════
# Preprint compilation
# ══════════════════════════════════════════════════════════════════════

def compile_preprint():
    """Concatenate all monthly rollups into a draft preprint document."""
    monthly_files = sorted(MONTHLY_DIR.glob("*.md"))
    if not monthly_files:
        return None
    out_lines = [
        "# HUNTER — Preprint Draft (auto-compiled)\n",
        f"*Compiled {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n",
        "\n## Abstract\n\n_TODO_\n",
        "\n## Introduction\n\n_See THEORY_CANON.md for canonical claims._\n",
        "\n## Empirical log by month\n",
    ]
    for mf in monthly_files:
        out_lines.append("\n" + mf.read_text() + "\n")
    out_lines.append("\n## Discussion & limitations\n\n_TODO_\n")

    out = PREPRINT_DIR / f"preprint_draft_{datetime.now().strftime('%Y%m%d')}.md"
    out.write_text("\n".join(out_lines))
    return out


# ══════════════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════════════

def main():
    _ensure_dirs()
    cmd = sys.argv[1] if len(sys.argv) > 1 else "incremental"

    if cmd in ("incremental", "--incremental"):
        h = generate_hypothesis_entries(force_all=False)
        c = generate_cycle_entries(force_all=False)
        s = generate_signal_entries(force_all=False)
        print(f"Wrote {h} hypothesis entries, {c} cycle entries, {s} signal entries.")
        print(f"Diary at: {DIARY_ROOT}/")

    elif cmd == "--all":
        h = generate_hypothesis_entries(force_all=True)
        c = generate_cycle_entries(force_all=True)
        s = generate_signal_entries(force_all=True)
        print(f"Regenerated {h} hypothesis, {c} cycle, {s} signal entries.")

    elif cmd == "weekly":
        iso = sys.argv[2] if len(sys.argv) > 2 else None
        f = build_weekly_rollup(iso)
        print(f"✓ Weekly rollup: {f}")

    elif cmd == "monthly":
        ym = sys.argv[2] if len(sys.argv) > 2 else None
        f = build_monthly_rollup(ym)
        print(f"✓ Monthly rollup: {f}")

    elif cmd == "preprint":
        f = compile_preprint()
        if f:
            print(f"✓ Preprint draft: {f}")
        else:
            print("No monthly rollups yet. Run: python research_diary.py monthly")
    else:
        print(__doc__)


if __name__ == "__main__":
    main()
